apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app-depolyment
  labels:
    app: dev-app
spec:
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-app
        image:  wil42/playground:v2
        ports:
        - containerPort: 8888